package(default_visibility = ['//saildb:__subpackages__'])

licenses(['notice'])
exports_files(['LICENSE'])

"""
  Note:
   - The following resources are used for basic test(s);
   - Will move to gtest in future iteration
"""

filegroup(
  name = 'env_data',
  srcs = ['.saildb.env'],
  visibility = ['//visibility:public'],
)
